#!/bin/zsh
# ADR Index Update Script
# Usage: update-index.sh [adr-directory]
# Output (stdout): path to updated index file
# Errors (stderr): directory not found etc. with exit 1

set -euo pipefail

if [ -n "${ADR_DIR:-}" ]; then
  : # use provided value
elif [ -n "${1:-}" ]; then
  ADR_DIR="$1"
else
  GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
  if [ -z "$GIT_ROOT" ]; then
    echo "Error: not inside a git repository. ADRs require <git-root>/docs/decisions/. Set ADR_DIR env var to override." >&2
    exit 1
  fi
  ADR_DIR="$GIT_ROOT/docs/decisions"
fi

if [ ! -d "$ADR_DIR" ]; then
  echo "Error: directory not found: $ADR_DIR" >&2
  exit 1
fi

if [ -f "$ADR_DIR/SKILL.md" ]; then
  echo "Error: $ADR_DIR contains SKILL.md (skill-definition directory, not an ADR archive)" >&2
  echo "Set ADR_DIR env var or pass an explicit ADR archive path." >&2
  exit 1
fi

INDEX_FILE="$ADR_DIR/README.md"

TEMP_FILE=$(mktemp)
TEMP_PROPOSED=$(mktemp)
TEMP_ACCEPTED=$(mktemp)
TEMP_DEPRECATED=$(mktemp)
TEMP_SUPERSEDED=$(mktemp)
TEMP_REJECTED=$(mktemp)

trap "rm -f $TEMP_FILE $TEMP_PROPOSED $TEMP_ACCEPTED $TEMP_DEPRECATED $TEMP_SUPERSEDED $TEMP_REJECTED" EXIT

cat > "$TEMP_FILE" <<'EOF'
# Architecture Decision Records

This directory contains important decisions about the project's architecture.

## ADR List

| Number | Title | Status | Date |
|--------|-------|--------|------|
EOF

while IFS= read -r adr_file; do
  FILENAME=$(basename "$adr_file")
  NUMBER=$(echo "$FILENAME" | grep -oE '^[0-9]{4}')

  IFS='|' read -r TITLE STATUS DATE <<< "$(awk '
    BEGIN { in_fm = 0; fm_seen = 0 }
    /^---[[:space:]]*$/ {
      if (fm_seen == 0) { in_fm = 1; fm_seen = 1; next }
      else if (in_fm) { in_fm = 0; next }
    }
    in_fm && /^status:/ && !s {
      s = $0
      sub(/^status:[[:space:]]*/, "", s)
      gsub(/^"|"$/, "", s)
    }
    in_fm && /^date:/ && !d {
      d = $0
      sub(/^date:[[:space:]]*/, "", d)
      gsub(/^"|"$/, "", d)
    }
    !in_fm && /^# / && !t { t = substr($0, 3) }
    END { print t "|" s "|" d }
  ' "$adr_file")"
  STATUS=${STATUS:-proposed}
  DATE=${DATE:-Not set}

  echo "| [$NUMBER]($FILENAME) | $TITLE | $STATUS | $DATE |" >> "$TEMP_FILE"

  case "$STATUS" in
    proposed*)   echo "$NUMBER|$TITLE" >> "$TEMP_PROPOSED" ;;
    accepted*)   echo "$NUMBER|$TITLE" >> "$TEMP_ACCEPTED" ;;
    deprecated*) echo "$NUMBER|$TITLE" >> "$TEMP_DEPRECATED" ;;
    superseded*) echo "$NUMBER|$TITLE" >> "$TEMP_SUPERSEDED" ;;
    rejected*)   echo "$NUMBER|$TITLE" >> "$TEMP_REJECTED" ;;
  esac
done < <(find "$ADR_DIR" -name "[0-9][0-9][0-9][0-9]-*.md" -type f | sort)

cat >> "$TEMP_FILE" <<'EOF'

## By Status

EOF

emit_status_section() {
  local heading="$1"
  local source_file="$2"
  if [ -s "$source_file" ]; then
    echo "### $heading" >> "$TEMP_FILE"
    echo "" >> "$TEMP_FILE"
    while IFS='|' read -r num title; do
      echo "- **$num**: $title" >> "$TEMP_FILE"
    done < <(sort "$source_file")
    echo "" >> "$TEMP_FILE"
  fi
}

emit_status_section "Proposed" "$TEMP_PROPOSED"
emit_status_section "Accepted" "$TEMP_ACCEPTED"
emit_status_section "Deprecated" "$TEMP_DEPRECATED"
emit_status_section "Superseded" "$TEMP_SUPERSEDED"
emit_status_section "Rejected" "$TEMP_REJECTED"

cat >> "$TEMP_FILE" <<'EOF'
## About MADR Format

This project uses [MADR (Markdown Any Decision Records)](https://adr.github.io/madr/) format, v4.

### How to Create an ADR

```bash
/adr "Decision Title"
```

### Status Meanings

- **Proposed**: Awaiting review
- **Accepted**: Approved, implementing or completed
- **Rejected**: Considered but not adopted
- **Deprecated**: Retired without a replacement ADR
- **Superseded**: Replaced by another ADR (e.g. `superseded by ADR-0042`)

---

*Last updated: {{UPDATE_DATE}}*
*Auto-generated by: update-index.sh*
EOF

UPDATE_DATE=$(date +%Y-%m-%d)
sed -i.bak "s/{{UPDATE_DATE}}/$UPDATE_DATE/g" "$TEMP_FILE"
rm -f "$TEMP_FILE.bak"

mv "$TEMP_FILE" "$INDEX_FILE"

echo "$INDEX_FILE"
