from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[3]
SKILL = REPO_ROOT / "skills" / "sdd-cmdc-opencode"
PARITY_SCRIPT = SKILL / "scripts" / "verify-install-parity.py"

EXECUTABLE_SHELLS = {
    Path("scripts/review-package"),
    Path("scripts/sdd-workspace"),
    Path("scripts/task-brief"),
}

# Text suffixes whose tracked files must be UTF-8. Sources already carry the
# ``text``/``eol=lf`` attributes; assertions must hold for tracked files only,
# so ignored caches and build output can never fail the contract.
TEXT_SUFFIXES = {".py", ".md", ".json"}


def git_ls_files_under(directory: Path) -> list[Path]:
    """List files tracked by git under ``directory``, relative to ``directory``."""
    result = subprocess.run(
        ["git", "ls-files", "--", str(directory)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    prefix = directory.relative_to(REPO_ROOT)
    return [Path(relative).relative_to(prefix) for relative in result.stdout.splitlines()]


def tracked_text_files(directory: Path = SKILL) -> list[Path]:
    return [
        directory / path
        for path in git_ls_files_under(directory)
        if path.suffix in TEXT_SUFFIXES
    ]


def tracked_runtime_files(directory: Path = SKILL) -> list[Path]:
    """Tracked files below the package that are not review-package payloads.

    The package manifest for a review package must come from ``git ls-files``
    so ignored caches and generated artifacts can never leak into a review.
    Review-package payload files (briefs, reports, review packages, progress
    ledgers) live under ``.superpowers/sdd/`` outside the package, so the
    package itself contributes no payload files.
    """
    return git_ls_files_under(directory)


def assert_lf_or_non_binary(path: Path) -> None:
    """Assert a tracked file has LF-only line endings unless it is binary."""
    data = path.read_bytes()
    if b"\x00" in data:
        return
    assert b"\r\n" not in data, f"CRLF byte sequence found in {path}"


def assert_no_generated_payload(paths: list[Path]) -> None:
    """Assert no path is a generated artifact, cache, or review-package payload."""
    for path in paths:
        parts = path.parts
        assert "__pycache__" not in parts, f"generated cache path: {path}"
        assert path.suffix != ".pyc", f"generated bytecode path: {path}"
        assert ".pytest_cache" not in parts, f"generated cache path: {path}"
        assert ".mypy_cache" not in parts, f"generated cache path: {path}"
        assert path.suffix not in {".log", ".diff", ".sqlite"}, (
            f"generated payload path: {path}"
        )


def test_shell_wrappers_have_lf_only_bytes() -> None:
    for relative in EXECUTABLE_SHELLS:
        data = (SKILL / relative).read_bytes()
        assert b"\r\n" not in data


def test_tracked_package_has_sources_and_no_generated_payload() -> None:
    tracked = git_ls_files_under(SKILL)
    assert Path("scripts/__init__.py") in tracked
    assert all("__pycache__" not in path.parts and path.suffix != ".pyc" for path in tracked)
    # The manifest must come from git ls-files so ignored caches and generated
    # artifacts can never be part of the package; review-package payloads
    # (briefs, reports, review packages, progress ledgers) live under
    # .superpowers/sdd/ outside the package.
    assert_no_generated_payload(tracked)


def test_text_sources_decode_as_utf8() -> None:
    for path in tracked_text_files(SKILL):
        path.read_text(encoding="utf-8")


def test_tracked_manifest_is_stable_and_complete() -> None:
    tracked = git_ls_files_under(SKILL)
    assert Path("SKILL.md") in tracked
    assert Path("scripts/cmdc-implementer.py") in tracked
    assert Path("tests/test_package_contract.py") in tracked
    assert tracked == sorted(tracked, key=str)


def test_tracked_manifest_excludes_generated_payload() -> None:
    assert_no_generated_payload(tracked_runtime_files())


def test_all_tracked_text_sources_are_lf_only() -> None:
    for path in tracked_text_files(SKILL):
        assert_lf_or_non_binary(path)


def test_install_parity_accepts_identical_trees(tmp_path: Path) -> None:
    source = tmp_path / "source"
    target = tmp_path / "target"
    (source / "scripts").mkdir(parents=True)
    target.mkdir()
    (source / "SKILL.md").write_text("contract\n", encoding="utf-8")
    (source / "scripts" / "adapter.py").write_text("print('ok')\n", encoding="utf-8")
    (target / "SKILL.md").write_text("contract\n", encoding="utf-8")
    (target / "scripts").mkdir()
    (target / "scripts" / "adapter.py").write_text("print('ok')\n", encoding="utf-8")

    result = subprocess.run(
        [sys.executable, str(PARITY_SCRIPT), str(source), str(target)],
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert "PARITY: OK" in result.stdout


def test_install_parity_rejects_symlink_target(tmp_path: Path) -> None:
    source = tmp_path / "source"
    target = tmp_path / "target"
    source.mkdir()
    target.mkdir()
    source_file = source / "adapter.py"
    source_file.write_text("source\n", encoding="utf-8")
    try:
        (target / "adapter.py").symlink_to(source_file)
    except OSError as exc:
        pytest.skip(f"symlink creation unavailable: {exc}")

    result = subprocess.run(
        [sys.executable, str(PARITY_SCRIPT), str(source), str(target)],
        capture_output=True,
        text=True,
    )

    assert result.returncode == 1
    assert "CHANGED adapter.py" in result.stdout


def test_install_parity_reports_changed_missing_and_extra_without_mutation(
    tmp_path: Path,
) -> None:
    source = tmp_path / "source"
    target = tmp_path / "target"
    source.mkdir()
    target.mkdir()
    (source / "adapter.py").write_text("source\n", encoding="utf-8")
    (source / "only-source.md").write_text("source-only\n", encoding="utf-8")
    (target / "adapter.py").write_text("target\n", encoding="utf-8")
    (target / "extra.py").write_text("extra\n", encoding="utf-8")
    before = {path: path.read_bytes() for path in target.rglob("*") if path.is_file()}

    result = subprocess.run(
        [sys.executable, str(PARITY_SCRIPT), str(source), str(target)],
        capture_output=True,
        text=True,
    )

    assert result.returncode == 1
    assert "CHANGED adapter.py" in result.stdout
    assert "MISSING only-source.md" in result.stdout
    assert "EXTRA extra.py" in result.stdout
    after = {path: path.read_bytes() for path in target.rglob("*") if path.is_file()}
    assert after == before
